os: linux
language: shell
install:
  - wget https://github.com/rust-lang/mdBook/releases/download/v0.3.7/mdbook-v0.3.7-x86_64-unknown-linux-gnu.tar.gz
  - tar -xzvf mdbook-*.tar.gz
script:
  ./mdbook build
before_deploy:
  openssl aes-256-cbc -K $encrypted_189e52c2c347_key -iv $encrypted_189e52c2c347_iv -in deploy_key.enc -out deploy_key -d
deploy:
  edge: true # use Travis-CI dpl v2
  provider: pages
  local_dir: book
  deploy_key: deploy_key
